stages:
  stageEndToEndTests:
    stepConditions:
      multicloudDeploy:
        configKeys:
          - 'cfTargets'
          - 'neoTargets'
      cloudFoundryDeploy:
        configKeys:
          - 'cfSpace'
          - 'cloudFoundry/space'
      healthExecuteCheck:
        configKeys:
          - 'testServerUrl'
      newmanExecute:
        filePatternFromConfig: 'newmanCollection'
        configKeys:
          - 'testRepository'
      uiVeri5ExecuteTests:
        filePattern: '**/conf.js'
        configKeys:
          - 'testRepository'
      npmExecuteEndToEndTests:
        configKeys:
          - 'appUrls'
  stageProductionDeployment:
    stepConditions:
      multicloudDeploy:
        configKeys:
          - 'cfTargets'
          - 'neoTargets'
      cloudFoundryDeploy:
        configKeys:
          - 'cfSpace'
          - 'cloudFoundry/space'
      neoDeploy:
        configKeys:
          - 'neo/account'
      healthExecuteCheck:
        configKeys:
          - 'testServerUrl'
      npmExecuteEndToEndTests:
        configKeys:
          - 'appUrls'
      githubPublishRelease:
        configKeys:
          - 'githubTokenCredentialsId'
  stageBackendIntegrationTests:
    extensionExists: true
    stepConditions:
      npmExecuteScripts:
        npmScripts: 'ci-itttttt-backend'
      mavenExecuteIntegration:
        filePattern: 'integration-tests/pom.xml'
  stageFrontendIntegrationTests:
    stepConditions:
      npmExecuteScripts:
        npmScripts: 'ci-it-frontend'
